"""Generate `src/maths/colormap_data.rs` from matplotlib's colour map definitions.

Run from the repository root with:

    uv run --with matplotlib==3.11.2 python crates/ironlab-scene/scripts/generate_colormaps.py

Each map is sampled at 256 evenly spaced points on [0, 1] and every channel is quantised
with round(255 * c). Viridis, magma, inferno and plasma are the CC0 tables by Nathaniel
Smith and Stefan van der Walt; cividis is the table by Jamie Nunez, Christopher Anderton
and Ryan Renslow (PLOS ONE, 2018) as shipped in matplotlib; coolwarm is Kenneth Moreno's
"smooth cool warm" diverging map as defined by matplotlib's segment data; gray is the
identity ramp.
"""

import pathlib

import matplotlib
import numpy as np

MAPS = [
    ("VIRIDIS", "viridis"),
    ("CIVIDIS", "cividis"),
    ("MAGMA", "magma"),
    ("INFERNO", "inferno"),
    ("PLASMA", "plasma"),
    ("COOLWARM", "coolwarm"),
    ("GRAY", "gray"),
]

OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "maths" / "colormap_data.rs"


def table(name):
    cmap = matplotlib.colormaps[name].resampled(256)
    rgba = cmap(np.linspace(0.0, 1.0, 256))
    return np.rint(rgba[:, :3] * 255.0).astype(int)


def main():
    lines = [
        "//! Colour map lookup tables (generated; do not edit by hand).",
        "//!",
        "//! Generated by `crates/ironlab-scene/scripts/generate_colormaps.py` from matplotlib "
        + matplotlib.__version__
        + ".",
        "//! See that script for the provenance and licence of each table.",
        "",
        "use super::colormap::Lut;",
        "",
    ]
    for const, name in MAPS:
        rows = table(name)
        lines.append(f"/// The `{name}` colour map, 256 sRGB entries from low to high.")
        lines.append(f"pub static {const}: Lut = [")
        for r, g, b in rows:
            lines.append(f"    [{r}, {g}, {b}],")
        lines.append("];")
        lines.append("")
    OUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
